version: '3'

services:

  db:
    image: mysql:8.0
    container_name: database
    restart: on-failure
    ports:
      - "3306:3306"
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes: 
      - db_data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - stack-network

  wordpress:
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress
    restart: on-failure
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - stack-network
    depends_on:
      - db

  webserver:
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    networks:
      - stack-network
    depends_on:
      - wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: on-failure
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    networks:
      - stack-network
    depends_on:
      - db

volumes:
  db_data:
  wordpress:

networks:
  stack-network:
    driver: bridge
